"""create_initial_jobtracker_schema

Revision ID: f5957d37d730
Revises: 
Create Date: 2026-09-14 18:47:25.277140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'f5957d37d730'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('canonical_company_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('source_platform', sa.String(length=100), nullable=False),
    sa.Column('job_description_raw', sa.Text(), nullable=True),
    sa.Column('primary_tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience_required_yrs', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('current_status', sa.Enum('APPLIED', 'OA_PENDING', 'INTERVIEW_ROUND', 'OFFER', 'REJECTED', 'WITHDRAWN', name='application_status'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_applications_applied_at', 'applications', [sa.literal_column('applied_at DESC')], unique=False)
    op.create_index('idx_applications_canonical_name', 'applications', ['canonical_company_name'], unique=False)
    op.create_index('idx_applications_status', 'applications', ['current_status'], unique=False)
    op.create_table('master_experience_vault',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('bullet_point', sa.Text(), nullable=False),
    sa.Column('tech_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('WORK_EXPERIENCE', 'PROJECT', 'SKILL', 'EDUCATION')", name='check_vault_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vault_embedding', 'master_experience_vault', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 10}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('worker_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('pipeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('APPLIED', 'OA_PENDING', 'INTERVIEW_ROUND', 'OFFER', 'REJECTED', 'WITHDRAWN', name='application_status'), nullable=True),
    sa.Column('to_status', sa.Enum('APPLIED', 'OA_PENDING', 'INTERVIEW_ROUND', 'OFFER', 'REJECTED', 'WITHDRAWN', name='application_status'), nullable=False),
    sa.Column('detected_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('MANUAL_DROP', 'GMAIL_WORKER', 'MANUAL_OVERRIDE', name='event_source'), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('llm_confidence', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_events_app_id', 'pipeline_events', ['application_id'], unique=False)
    op.create_index('idx_pipeline_events_created', 'pipeline_events', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('resume_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('retrieved_vault_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_user_edited', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resume_snapshots_app_id', 'resume_snapshots', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_resume_snapshots_app_id', table_name='resume_snapshots')
    op.drop_table('resume_snapshots')
    op.drop_index('idx_pipeline_events_created', table_name='pipeline_events')
    op.drop_index('idx_pipeline_events_app_id', table_name='pipeline_events')
    op.drop_table('pipeline_events')
    op.drop_table('worker_config')
    op.drop_index('idx_vault_embedding', table_name='master_experience_vault', postgresql_using='ivfflat', postgresql_with={'lists': 10}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('master_experience_vault')
    op.drop_index('idx_applications_status', table_name='applications')
    op.drop_index('idx_applications_canonical_name', table_name='applications')
    op.drop_index('idx_applications_applied_at', table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
